project:
  type: website
  output-dir: _site   # GitHub builds from this folder

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd#top
      - text: "About"
        href: index.qmd#about
      - text: "Experience"
        href: index.qmd#experience
      - text: "Projects"
        href: index.qmd#projects
      - text: "Contact"
        href: index.qmd#contact
    right:
      - icon: github
        href: https://github.com/devarshi2011
        aria-label: GitHub

format:
  html:
    theme: flatly        
    css: styles.css
